import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Todo List",
  description: "Generated by AlflenGabriel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-zinc-200`}>{children}</body>
    </html>
  );
}
